### ISSUE TITLE
What makes this official?

### ISSUE THREAD

**Issue by Bilge** [odb/official-bash-logo#4]
Besides the fact that you say it is? This imagery does not appear anywhere in the software itself, nor on the [GNU website](https://www.gnu.org/software/bash/), and it seems most of the sources now including it only did so after this repository was published claiming to be some sort of authority.

**Comment by jdorfman** [comment]
* https://en.wikipedia.org/wiki/Bash_(Unix_shell)
* https://github.com/odb/official-bash-logo/blob/master/assets/copyright-agreement.pdf
* https://shop.fsf.org/stickers/bash-logo-sticker-pack
* https://tiswww.case.edu/php/chet/bash/bashtop.html
